# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pass_reqs', '0003_auto_20171201_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passreqs',
            options={'ordering': ['-website']},
        ),
        migrations.RemoveField(
            model_name='website',
            name='passreqs',
        ),
        migrations.AddField(
            model_name='passreqs',
            name='website',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pass_reqs.Website'),
        ),
    ]
