# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_reqs', '0004_auto_20171204_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='passreqs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='passreqs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
