# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass_reqs', '0005_auto_20171204_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='passreqs',
            name='capitals',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='passreqs',
            name='complex',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='passreqs',
            name='special_characters',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
